apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: enn-monitor-config-service-web
    labels:
        name: enn-monitor-config-service-web
    namespace: '%NAMESPACE%'
spec:
    replicas: %REPLICSNUM%
    strategy:
        type: RollingUpdate
        maxUnavailable: 1
        maxSurge: 0
    template:
        metadata:
            labels:
                name: enn-monitor-config-service-web
        spec:
            containers:
                -
                    name: enn-monitor-config-service-web
                    image: '%IMAGEURL%'
                    resources:
                        requests:
                            memory: %MEMREQ%
                            cpu: %CPUREQ%
                        limits:
                            memory: %MEMLIMIT%
                            cpu: %CPULIMIT%
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-config-service-web
