apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-alarm-config-server
    labels:
        name: enn-monitor-alarm-config-server
    namespace: %NAMESPACE%
spec:
    ports:
        -
            port: %CONFIGLISTENPORT%
    selector:
        name: enn-monitor-alarm-config-server

