apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: enn-monitor-tracing
    namespace: %NAMESPACE%
    labels:
        name: enn-monitor-tracing
spec:
    replicas: %REPLICSNUM%
    template:
        metadata:
            labels:
                name: enn-monitor-tracing
        spec:
            containers:
                -
                    name: enn-monitor-tracing
                    imagePullPolicy: Always
                    image: %IMAGEURL%
                    resources:
                        requests:
                            memory: %MEMREQ%
                            cpu: %CPUREQ%
                        limits:
                            memory: %MEMLIMIT%
                            cpu: %CPULIMIT%
                    ports:
                        -
                            containerPort: %LISTENPORT%
                            protocol: TCP
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-tracing
                        -
                            name: GATEWAYTOKEN
                            value: "C6368842504E634195CF7578371C67BE"
                    command:
                        - "java"
                        - "-jar"
                        - "/opt/enn-monitor-tracing-1.0.0.jar"
                        - "--config_service_host"
                        - "10.19.248.200"
                        - "--config_service_port"
                        - "29309"
                        - "--trace_host"
                        - "enn-monitor-trace-data-api.monitor-system-trace"
                        - "--trace_port"
                        - "8888"


