apiVersion: v1
kind: Service
metadata:
    name: chandao
    namespace: '%NAMESPACE%'
    labels:
        name: chandao
spec:
    type: NodePort
    ports:
        -
            port: 80
            nodePort: 30201
    selector:
        name: chandao

