apiVersion: v1
kind: Storage
metadata:
  name: %NAMESPACE%-chandao
  namespace: %NAMESPACE%
spec:
  type: RBD
  accessModes: ReadWriteMany
  persisted: true
  unshared: true
  resources:
    requests:
      storage: 200Gi
