apiVersion: v1
kind: Service
metadata:
    labels:
        name: monitoring-grafana
    name: monitoring-grafana
    namespace: %NAMESPACE%
spec:
    ports:
        -
            name: p1
            port: 3000
            nodePort: 29008
    type: NodePort
    selector:
        name: Grafana

