apiVersion: v1
kind: Service
metadata:
    name: zk%ZK_NUM%
    namespace: %NAMESPACE%
    labels:
        app: hadoop-ha
        name: zk%ZK_NUM%
        tier: backend
spec:
    ports:
        -
            name: p1
            port: 2888
        -
            name: p2
            port: 3888
        -
            name: p3
            port: 2181
    selector:
        name: zk%ZK_NUM%

