apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-etl-metrics
  namespace: monitor-system-metrics
  labels:
    name: spark-etl-metrics
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spark-etl-metrics
    spec:
      containers:
        - name: spark-etl-metrics
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: %CPU_LIMIT_METRIC%
              memory: %MEM_LIMIT_METRIC%
            requests:
              cpu: %CPU_REQ_METRIC%
              memory: %MEM_REQ_METRIC%
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: "METANAME"
              value: "spark-etl-metrics"
            - name: CEPH_PATH
              value: %CEPH_PATH%
            - name: WORKSPACE
              value: %WORKSPACE%
            - name: JOB_JAR
              value: %JOB_JAR%
            - name: JOB_SH
              value: %JOB_SH%
            - name: SPARK_MASTER
              value: %SPARK_MASTER%
            - name: MAIN_CLASS
              value: %MAIN_CLASS%
            - name: TOTAL_CORES
              value: %TOTAL_CORES%
            - name: EXECUTOR_MEM
              value: %EXECUTOR_MEM%
            - name: EXECUTOR_CORES
              value: %EXECUTOR_CORES%
            - name: MAX_RATE
              value: %MAX_RATE%
            - name: KAFKA
              value: %KAFKA%
            - name: PROM_PUSH
              value: "%PROM_PUSH%"
            - name: OPENTSDB_URL
              value: %OPENTSDB_URL%
            - name: APIUSER
              value: %APIUSER%
            - name: APISERVER
              value: %APISERVER%
            - name: APIPASS
              value: %APIPASS%
            - name: TOPIC_NAME
              value: %TOPIC_NAME%
            - name: ASYNC
              value: "%ASYNC%"
            - name: GROUP_ID
              value: %GROUP_ID%
            - name: RDD_PARTITION
              value: %RDD_PARTITION%
            - name: GATEWAYTOKEN
              value: "4B2603051E64250C2DC528B325AA242A"
          image: %IMAGEURL%
          ports:
            - containerPort: 4040
          volumeMounts:
            - name: monitor-etl-metrics
              mountPath: /opt/ceph
          command:
            - /opt/start.sh
      storage:
        - name: monitor-etl-metrics
