apiVersion: v1
kind: Service
metadata:
  name: spark-etl-log-system
  namespace: monitor-system-log
  labels:
    app: spark-etl-log-system
    name: spark-etl-log-system
    tier: backend
spec:
  externalIPs:
    - 10.19.137.148
  ports:
    - name: application-ui
      port: 24041
      targetPort: 4040
  selector:
    name: spark-etl-log-system
