apiVersion: v1
kind: Service
metadata:
  name: datanode3
  namespace: %NAMESPACE%
  labels:
    app: hadoop-ha
    name: datanode3
    tier: backend
spec:
  ports:
    #datanode
    - name: p1
      port: 50010
    - name: p2
      port: 50020
    - name: p3
      port: 50075
    - name: p4
      port: 50475
    # nodemanager
    - name: p5
      port: 8040
    - name: p6
      port: 8041
    - name: p7
      port: 8042
    - name: journalnode
      port: 8485
  selector:                                                   
    app: hadoop-ha                                              
    name: hadoop-datanode3-rc                                  
    tier: backend 
