apiVersion: v1
kind: Service
metadata:
  name: namenode1
  namespace: %NAMESPACE%
  labels:
    app: hadoop-ha
    name: hadoop-namenode1-svc
    tier: backend
spec:
# clusterIP: 45.79.79.237
  type: LoadBalancer
  ports:
    # namenode
    - name: p1
      port: 50070
      targetPort: 50070
    - name: p2
      port: 50470
    - name: p3
      port: 8020
    # journalnode
    - name: p4
      port: 8485
    - name: p5
      port: 8480
    # yarn
    - name: p6
      port: 8030
    - name: p7
      port: 8031
    - name: p8
      port: 8088
    - name: p9
      port: 8033
    - name: p10
      port: 10020
    - name: p11
      port: 19888
    - name: ssh
      port: 2222
      targetPort: 22
  #k8s集群节点ip                                                                   
  externalIPs:                                                   
    - %NAMENODE_EXIP%
  selector:                                                
    app: hadoop-ha                                                           
    name: hadoop-namenode1-rc                               
    tier: backend  
