apiVersion: v1
kind: Pod
metadata:
  name: namenode1
  namespace: %NAMESPACE%
  labels:
    app: hadoop-ha
    name: hadoop-namenode1-rc
    tier: backend
spec:
  nodeName: %HOST%
  containers:
    - name: namenode1
      image: %IMAGEURL%
      imagePullPolicy: IfNotPresent
      volumeMounts:
      - mountPath: /meiling-test
        name: meiling-volume
      ports:
        - containerPort: 50070
        - containerPort: 50470
        - containerPort: 8020
        - containerPort: 8485
        - containerPort: 8480
        - containerPort: 8030
        - containerPort: 8031
        - containerPort: 8088
        - containerPort: 8033
        - containerPort: 10020
        - containerPort: 19888
        - containerPort: 22
  volumes:
  - name: meiling-volume
    hostPath:
      # directory location on host
      path: /root/meiling-tests

