apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: enn-monitor-trace-data-api
    namespace: monitor-system-trace
    labels:
        name: enn-monitor-trace-data-api
spec:
    replicas: 2
    template:
        metadata:
            labels:
                name: enn-monitor-trace-data-api
        spec:
            containers:
                -
                    name: enn-monitor-trace-data-api
                    imagePullPolicy: Always
                    image: 10.19.248.200:29006/enncloud/enn-monitor-trace-data-api:0.9.2.release
                    resources:
                        requests:
                            memory: 1000Mi
                            cpu: 500m
                        limits:
                            memory: 3000Mi
                            cpu: 1000m
                    ports:
                        -
                            containerPort: 8888
                            protocol: TCP
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-trace-data-api
                    command:
                        - "java"
                        - "-cp"
                        - "/opt/enn-monitor-trace-data-api.jar"
                        - "enn.monitor.trace.dataapi.DataApiServer"
                        - "--enable_metrics"
                        - "--elasticSearch_host"
                        - "elasticsearch-client.monitor-essential-service"
                        - "--elasticSearch_port"
                        - "9200"
                        - "--token"
                        - "micklongen-gateway-server"
                        - "--gateway_server"
                        - "enn-monitor-security-gateway-server.monitor-system-security"
                        - "--gatewayPort"
                        - "10000"

