apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-metric-app-streaming
    labels:
        name: enn-monitor-metric-app-streaming
    namespace: %NAMESPACE%
spec:
    type: NodePort
    ports:
        -
            name: p1
            port: %LISTENPORT%
            nodePort: %EXTERNPORT%
    selector:
        name: enn-monitor-metric-app-streaming

