apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-log-config-web
    labels:
        name: enn-monitor-log-config-web
    namespace: '%NAMESPACE%'
spec:
    type: NodePort
    ports:
        -
            port: 8080
            nodePort: %EXTERNPORT%
    selector:
        name: enn-monitor-log-config-web

