apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitor-security-mongo-pv
  namespace: %NAMESPACE%
  annotations:
    io.enndata.user/alpha-pvhostpathmountpolicy: "keep"
    io.enndata.user/alpha-pvhostpathquotaforonepod: "true"
  labels:
    name: monitor-security-mongo
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /
