apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: enn-monitor-metric-kubelet-streaming
    labels:
        name: enn-monitor-metric-kubelet-streaming
    namespace: %NAMESPACE%
spec:
    replicas: %REPLICSNUM%
    template:
        metadata:
            labels:
                name: enn-monitor-metric-kubelet-streaming
        spec:
            containers:
                -
                    name: enn-monitor-metric-kubelet-streaming
                    image: %IMAGEURL%
                    resources:
                        requests:
                            memory: %MEMREQ%
                            cpu: %CPUREQ%
                        limits:
                            memory: %MEMLIMIT%
                            cpu: %CPULIMIT%
                    ports:
                        -
                            containerPort: %LISTENPORT%
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-metric-kubelet-streaming
                        -
                            name: GATEWAYTOKEN
                            value: '4B2603051E64250C2DC528B325AA242A'
                    command:
                        - /bin/sh
                        - '-c'
                    args:
                        - 'cp /opt/conf/start.sh /opt/start.sh; chmod a+x /opt/start.sh; /opt/start.sh'
                    volumeMounts:
                        - 
                            name: config-volume
                            mountPath: /opt/conf
            volumes:
                - 
                    name: config-volume
                    configMap:
                        name: metric-kubelet-streaming-conf
