apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-log-config-cache-server
    labels:
        name: enn-monitor-log-config-cache-server
    namespace: %NAMESPACE%
spec:
    type: NodePort
    ports:
        -
            name: port
            port: %LISTENPORT%
            nodePort: %EXTERNPORT%
    selector:
        name: enn-monitor-log-config-cache-server

