apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-alarm-ticket-server
    labels:
        name: enn-monitor-alarm-ticket-server
    namespace: %NAMESPACE%
spec:
    ports:
        -
            port: %TICKETLISTENPORT%
    selector:
        name: enn-monitor-alarm-ticket-server

