apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: enn-monitor-trace-data-api
    namespace: %NAMESPACE%
    labels:
        name: enn-monitor-trace-data-api
spec:
    replicas: %REPLICSNUM%
    template:
        metadata:
            labels:
                name: enn-monitor-trace-data-api
        spec:
            containers:
                -
                    name: enn-monitor-trace-data-api
                    imagePullPolicy: Always
                    image: %IMAGEURL%
                    resources:
                        requests:
                            memory: %MEMREQ%
                            cpu: %CPUREQ%
                        limits:
                            memory: %MEMLIMIT%
                            cpu: %CPULIMIT%
                    ports:
                        -
                            containerPort: %LISTENPORT%
                            protocol: TCP
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-trace-data-api
                    command:
                        - "java"
                        - "-cp"
                        - "/opt/enn-monitor-trace-data-api.jar"
                        - "enn.monitor.trace.dataapi.DataApiServer"
                        - "--enable_metrics"
                        - "--elasticSearch_host"
                        - "elasticsearch-client.monitor-essential-service"
                        - "--elasticSearch_port"
                        - "9200"
                        - "--token"
                        - "micklongen-gateway-server"
                        - "--gateway_server"
                        - "enn-monitor-security-gateway-server.monitor-system-security"
                        - "--gatewayPort"
                        - "10000"

