apiVersion: v1
kind: Service
metadata:
    labels:
        name: laikang-grafana
    name: laikang-grafana
    namespace: g-laikang-sh-qa
spec:
    ports:
        -
            name: p1
            port: 3000
            nodePort: 31008
    type: NodePort
    selector:
        name: laikang-grafana

