apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: enn-monitor-test-log
    labels:
        name: enn-monitor-test-log
    namespace: %NAMESPACE%
spec:
    selector:
        matchLabels:
            name: enn-monitor-test-log
    template:
        metadata:
            name: enn-monitor-test-log
            labels:
                name: enn-monitor-test-log
            namespace: %NAMESPACE%
        spec:
            containers:
                -
                    name: enn-monitor-test-log
                    image: %IMAGEURL%
                    resources:
                        requests:
                            memory: %MEMREQ%
                            cpu: %CPUREQ%
                        limits:
                            memory: %MEMLIMIT%
                            cpu: %CPULIMIT%
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-test-log
                        -
                            name: LOGPATTERN
                            value: '^(?<dateTime>[\d\-]+[\s]+[\d\:\.]+)[\s]*\[(?<threadName>[^\]\s]*)\][\s]*(?<logLevel>[^\s]*)[\s]*(?<position>[^\s]*)[\s\-]*\[(?<traceId>[^\]]*)\][\s\-]*\[(?<parentPod>[^\]]*)\][\s\-]*(?<log>.*)$'
                        -
                            name: LOGASSEMBLE
                            value: '%logLevel%,%position%,%log%,%dateTime%,%traceId%,%parentPod%,%threadName%'
                    command:
                        - "java"
                        - "-cp"
                        - "/opt/enn-monitor-test-log.jar"
                        - "enn.monitor.test.log.server.EnnMonitorTestLogServer"
                        - "--batchNum"
                        - "3000"
                        - "--waitMills"
                        - "200"
