apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-security-gateway-server
    labels:
        name: enn-monitor-security-gateway-server
    namespace: %NAMESPACE%
spec:
    type: NodePort
    ports:
        -
            name: p1
            port: %ENNMONITORSECURITYGATEWAYLISTENPORT%
            nodePort: %PORT%
    selector:
        name: enn-monitor-security-gateway-server

