apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: enn-monitor-security-gateway-server
    labels:
        name: enn-monitor-security-gateway-server
    namespace: %NAMESPACE%
spec:
    replicas: %REPLICSNUM%
    template:
        metadata:
            labels:
                name: enn-monitor-security-gateway-server
        spec:
            containers:
                -
                    name: enn-monitor-security-gateway-server
                    image: %IMAGEURL%
                    imagePullPolicy: Always
                    resources:
                        requests:
                            memory: %MEMREQ%
                            cpu: %CPUREQ%
                        limits:
                            memory: %MEMLIMIT%
                            cpu: %CPULIMIT%
                    ports:
                        -
                            containerPort: %ENNMONITORSECURITYGATEWAYLISTENPORT%
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-security-gateway-server
                        -
                            name: GATEWAYTOKEN
                            value: '865A6F85A8DA220FD130384FA2EABCB8'
                    command:
                        - "java"
                        - "-Xms1000m"
                        - "-Xmx2000m"
                        - "-cp"
                        - "/opt/enn-monitor-security-gateway-server.jar"
                        - "enn.monitor.security.gateway.server.EnnMonitorSecurityGatewayServer"
                        - "--workThreadNum"
                        - "16"
                        - "--listen_port"
                        - "%ENNMONITORSECURITYGATEWAYLISTENPORT%"
                        - "--kafkaUrl"
                        - "%KAFKAURL%"
                        - "--config_service_ip"
                        - "enn-monitor-config-service-server.monitor-system-config"
                        - "--config_service_port"
                        - "10000"
                        - "--config_business_ip"
                        - "enn-monitor-config-business-server.monitor-system-config"
                        - "--config_business_port"
                        - "10000"
