apiVersion: v1
kind: ReplicationController
metadata:
    name: enn-monitor-alarm-web
    labels:
        name: enn-monitor-alarm-web
    namespace: '%NAMESPACE%'
spec:
    replicas: %REPLICSNUM%
    selector:
        name: enn-monitor-alarm-web
    template:
        metadata:
            labels:
                name: enn-monitor-alarm-web
        spec:
            containers:
                -
                    name: enn-monitor-alarm-web
                    image: '%IMAGEURL%'
                    resources:
                        requests:
                            memory: %MEMREQ%
                            cpu: %CPUREQ%
                        limits:
                            memory: %MEMLIMIT%
                            cpu: %CPULIMIT%
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-alarm-web
