apiVersion: v1
kind: Service
metadata:
    name: elasticsearch-client
    namespace: %NAMESPACE%
    labels:
        name: elasticsearch-client
spec:
    type: NodePort
    ports:
        -
            name: db
            port: 9200
            nodePort: 29400
        -
            name: transport
            port: 9300
            nodePort: 29401
    selector:
        name: elasticsearch-client

