apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitor-elasticsearch-data-pvc
  namespace: %NAMESPACE%
  labels:
    name: monitor-elasticsearch-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      name: monitor-elasticsearch-data

