apiVersion: v1
kind: Service
metadata:
    name: elasticsearch-master-%index%
    namespace: %NAMESPACE%
    labels:
        name: elasticsearch-master-%index%
spec:
    ports:
        -
            name: db
            port: 9200
        -
            name: transport
            port: 9300
    selector:
        name: elasticsearch-master-%index%

