apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitor-elasticsearch-master-pvc-%index%
  namespace: %NAMESPACE%
  labels:
    name: monitor-elasticsearch-master-%index%
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: monitor-elasticsearch-master-%index%

