apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spark-etl-app
  namespace: monitor-system-metrics
  labels:
    name: spark-etl-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spark-etl-app
    spec:
      containers:
        - name: spark-etl-app
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 300m
              memory: 1Gi
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: "METANAME"
              value: "spark-etl-app"
            - name: CEPH_PATH
              value: /opt/ceph
            - name: WORKSPACE
              value: /opt/workspace
            - name: JOB_JAR
              value: enn-monitor-metric-app-streaming-0.10.0-SNAPSHOT.jar
            - name: JOB_SH
              value: start-etl-app_1.sh
            - name: SPARK_MASTER
              value: spark://pre2-master1.monitor-essential-service:7077,pre2-master2.monitor-essential-service:7077,pre2-master3.monitor-essential-service:7077
            - name: MAIN_CLASS
              value: enn.monitor.metric.app.streaming.Collector
            - name: TOTAL_CORES
              value: 2
            - name: EXECUTOR_MEM
              value: 1g
            - name: EXECUTOR_CORES
              value: 1
            - name: MAX_RATE
              value: 500
            - name: KAFKA
              value: pre2-kafka1.monitor-essential-service:9092,pre2-kafka2.monitor-essential-service:9092,pre2-kafka3.monitor-essential-service:9092
            - name: TOPIC_NAME
              value: monitor-app
            - name: GROUP_ID
              value: etl2
            - name: OPENTSDB
              value: monitoring-opentsdb.monitor-essential-service:4242
            - name: GATEWAYTOKEN
              value: "CA4B7757AEEAA7EA547776653906EA42"
          image: 10.19.140.200:29006/enncloud/monitor-streaming-jobs:0.9.0.release
          ports:
            - containerPort: 4040
          volumeMounts:
            - name: monitor-etl-metrics
              mountPath: /opt/ceph
          command:
            - /opt/start.sh
      storage:
        - name: monitor-etl-metrics
