apiVersion: v1
kind: ReplicationController
metadata:
    name: enn-monitor-alarm-ticket-server-gateway
    labels:
        name: enn-monitor-alarm-ticket-server-gateway
    namespace: %NAMESPACE%
spec:
    replicas: %REPLICSNUM%
    selector:
        name: enn-monitor-alarm-ticket-server-gateway
    template:
        metadata:
            labels:
                name: enn-monitor-alarm-ticket-server-gateway
        spec:
            containers:
                -
                    name: enn-monitor-alarm-ticket-server-gateway
                    image: %IMAGEURL%
                    resources:
                        requests:
                            memory: %MEMREQ%
                            cpu: %CPUREQ%
                        limits:
                            memory: %MEMLIMIT%
                            cpu: %CPULIMIT%
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-alarm-ticket-server-gateway
                        -
                            name: LOGPATTERN
                            value: '^(?<dateTime>[\d\-]+[\s]+[\d\:\.]+)[\s]*\[(?<threadName>[^\]\s]*)\][\s]*(?<logLevel>[^\s]*)[\s]*(?<position>[^\s]*)[\s\-]*\[(?<traceId>[^\]]*)\][\s\-]*\[(?<parentPod>[^\]]*)\][\s\-]*(?<log>.*)$'
                        -
                            name: LOGASSEMBLE
                            value: '%logLevel%,%position%,%log%,%dateTime%,%traceId%,%parentPod%,%threadName%'
                    command:
                        - "java"
                        - "-cp"
                        - "/opt/enn-monitor-alarm-ticket-server-gateway.jar"
                        - "enn.monitor.alarm.ticket.gateway.web.EnnMonitorAlarmTicketGatewayServer"
                        - "--listen_port"
                        - "%TICKETLISTENPORT%"
                        - "--enable_metrics"
                        - "--token"
                        - "micklongen-alarm-ticket-server-gateway"
                        - "--gateway_server"
                        - "enn-monitor-security-gateway-server.monitor-system-security"
                        - "--gatewayPort"
                        - "10100"
                        - "--ticket_server"
                        - "enn-monitor-alarm-ticket-server"
                        - "--ticket_port"
                        - "10000"
