apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-log-analyse-template
    labels:
        name: enn-monitor-log-analyse-template
    namespace: %NAMESPACE%
spec:
    type: NodePort
    ports:
        -
            name: p1
            port: %SPARKLISTENPORT%
            nodePort: %SPARKEXTERNPORT%
        -
            name: p2
            port: %SVRLISTENPORT%
            nodePort: %SVREXTERNPORT%
    selector:
        name: enn-monitor-log-analyse-template

