apiVersion: v1
kind: Service
metadata:
    name: monitoring-opentsdb
    namespace: '%NAMESPACE%'
    labels: null
spec:
    ports:
        -
            name: p1
            port: 4242
            nodePort: %PORT%
    type: NodePort
    selector:
        name: monitoring-opentsdb

