apiVersion: v1
kind: Pod
metadata:
  name: master
  namespace: %NAMESPACE%
  labels:
    app: hbase
    name: hbase-master-rc
    tier: backend
spec:
  containers:
    - name: master
      image: %IMAGEURL%
      imagePullPolicy: IfNotPresent
      env: 
      - name: NAMESPACE
        value: "%NAMESPACE%"
      - name: HDFSPATH
        value: "%HDFS_ADDR%"
      - name: ZKNAME
        value: "%ZK_NODES%"
      ports:
        - containerPort: 60000
        - containerPort: 60010
        - containerPort: 60020
        - containerPort: 60030
        - containerPort: 16010
        - containerPort: 16020
        - containerPort: 16030
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
#        - containerPort: 22
  nodeName: %HOST%
