apiVersion: v1
kind: Service
metadata:
  name: slave%SLAVE_NUM%
  namespace: %NAMESPACE%
  labels:
    app: hbase
    name: slave%SLAVE_NUM%
    tier: backend
spec:
  ports:
    - name: p8
      port: 60020
    - name: p9
      port: 60030
    - name: p10
      port: 2181
    - name: p11
      port: 2888
    - name: p12
      port: 3888
    - name: t1
      port: 16010
    - name: t2
      port: 16020
    - name: t3
      port: 16030
#    - name: ssh
#      port: 2222
#      targetPort: 22
  selector:
    app: hbase
    name: hbase-slave%SLAVE_NUM%-rc
    tier: backend
