apiVersion: v1
kind: Pod
metadata:
  name: slave%SLAVE_NUM%
  namespace: %NAMESPACE%
  labels:
    app: hbase
    name: hbase-slave%SLAVE_NUM%-rc
    tier: backend
spec:
  containers:
    - 
      name: slave%SLAVE_NUM%
      image: %IMAGEURL%
      imagePullPolicy: IfNotPresent
      env:
      - name: NAMESPACE
        value: "%NAMESPACE%"
      - name: HDFSPATH
        value: "%HDFS_ADDR%"
      - name: ZKNAME
        value: "%ZK_NODES%"
      ports: 
        - containerPort: 60020
        - containerPort: 60030
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        - containerPort: 16010
        - containerPort: 16020
        - containerPort: 16030
#        - containerPort: 22
  nodeName: %HOST%

