apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: kibana-logging
    namespace: '%NAMESPACE%'
    labels:
        name: kibana-logging
        version: v1
        kubernetes.io/cluster-service: 'true'
spec:
    replicas: 3
    template:
        metadata:
            labels:
                name: kibana-logging
        spec:
            containers:
                -
                    name: kibana-logging
                    image: '%imageurl%'
                    resources:
                        requests:
                            memory: %MEMREQ%
                            cpu: %CPUREQ%
                        limits:
                            memory: %MEMLIMIT%
                            cpu: %CPULIMIT%
                    ports:
                        -
                            containerPort: 30561
                    volumeMounts:
                        - 
                            name: config-volume
                            mountPath: /opt/conf
            volumes:
                - 
                    name: config-volume
                    configMap:
                        name: kibana-conf

