apiVersion: v1
kind: Service
metadata:
    name: kibana-logging
    namespace: '%NAMESPACE%'
    labels:
        name: kibana-logging
        kubernetes.io/cluster-service: 'true'
        kubernetes.io/name: Elasticsearch
spec:
    type: NodePort
    ports:
        -
            port: 30561
            nodePort: 30561
    selector:
        name: kibana-logging

