apiVersion: v1
kind: Service
metadata:
    name: enn-monitor-config-business-server
    labels:
        name: enn-monitor-config-business-server
    namespace: %NAMESPACE%
spec:
    type: NodePort
    ports:
        -
            name: p1
            port: %LISTENPORT%
            nodePort: 30137
    selector:
        name: enn-monitor-config-business-server

