apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: enn-monitor-config-business-server
    labels:
        name: enn-monitor-config-business-server
    namespace: %NAMESPACE%
spec:
    replicas: %REPLICSNUM%
    strategy:
        type: RollingUpdate
        maxUnavailable: 1
        maxSurge: 0
    template:
        metadata:
            labels:
                name: enn-monitor-config-business-server
        spec:
            containers:
                -
                    name: enn-monitor-config-business-server
                    image: %IMAGEURL%
                    imagePullPolicy: Always
                    resources:
                        requests:
                            memory: %MEMREQ%
                            cpu: %CPUREQ%
                        limits:
                            memory: %MEMLIMIT%
                            cpu: %CPULIMIT%
                    ports:
                        -
                            containerPort: %LISTENPORT%
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: PODNAME
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.name
                        -
                            name: APPNAME
                            value: enn-monitor-config-business-server
                        -
                            name: GATEWAYTOKEN
                            value: '1C38E872FB86DBE039236240D6AAF15C'
                    command:
                        - "java"
                        - "-Xms512m"
                        - "-Xmx1000m"
                        - "-cp"
                        - "/opt/enn-monitor-config-business-server.jar"
                        - "enn.monitor.config.business.server.EnnMonitorConfigBusinessServer"
                        - "--workThreadNum"
                        - "16"
                        - "--listen_port"
                        - "%LISTENPORT%"
                        - "--mongoUrl"
                        - "mongodb://mongo1.monitor-essential-service:27017,mongo2.monitor-essential-service:27017,mongo3.monitor-essential-service:27017/EnnMonitorConfigBusiness"
                        - "--dbName"
                        - "EnnMonitorConfigBusiness"
