apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: elasticsearch-fluent
    namespace: '%NAMESPACE%'
    labels:
        k8s-app: elasticsearch-fluent
spec:
    selector:
        matchLabels:
            k8s-app: elasticsearch-fluent
    template:
        metadata:
            name: elasticsearch-fluent
            namespace: '%NAMESPACE%'
            labels:
                k8s-app: elasticsearch-fluent
        spec:
            containers:
                -
                    image: '%IMAGEURL%'
#                    imagePullPolicy: Always
                    name: elasticsearch-fluent
                    resources:
                        requests:
                            memory: %MEMREQ%
                            cpu: %CPUREQ%
                        limits:
                            memory: %MEMLIMIT%
                            cpu: %CPULIMIT%
                    securityContext:
                        privileged: true
                    env:
                        -
                            name: NAMESPACE
                            valueFrom:
                                fieldRef:
                                    fieldPath: metadata.namespace
                        -
                            name: GATEWAYSERVER
                            value: '%GATEWAYSERVER%'
                        -
                            name: GATEWAYPORT
                            value: '%GATEWAYPORT%'
                        -
                            name: APIURL
                            value: '%APIURL%'
                        -
                            name: CLUSTERNAME
                            value: '%CLUSTERNAME%'
                        -
                            name: USERNAME
                            value: '%USERNAME%'
                        -
                            name: PASSWD
                            value: '%PASSWD%'
                        -
                            name: DOCKERPATH
                            value: '%DOCKERLOGPATH%/containers'
                        -
                            name: GATEWAYTOKEN
                            value: 'D4AFA3F7C56544A84E289D5D7797A785'
                    volumeMounts:
                        -
                            name: var-log
                            mountPath: /fb-var/log
                        -
                            name: var-log-pod
                            mountPath: /var/log/pods
                        -
                            name: pos-storage
                            mountPath: /data/pos
                        -
                            name: data
                            mountPath: %DOCKERLOGPATH%
                            readOnly: true
                        - 
                            name: config-volume
                            mountPath: /opt/conf
            volumes:
                -
                    name: var-log
                    hostPath:
                        path: /var/log
                -
                    name: var-log-pod
                    hostPath:
                        path: /var/log/pods
                -
                    name: pos-storage
                    hostPath:
                        path: /mnt/%NAMESPACE%/elasticsearch-fluent
                -
                    name: data
                    hostPath:
                        path: %DOCKERLOGPATH%
                - 
                    name: config-volume
                    configMap:
                        name: fluentd-conf

